export const FETCH_LAYOUT_DATA = "FETCH_LAYOUT_DATA";
export const MODIFY_LAYOUT = "MODIFY_LAYOUT";
export const FETCH_MAIN_CONTENT_DATA = "FETCH_MAIN_CONTENT_DATA";
export const FETCH_QUIZ_STATIC_DATA = 'FETCH_QUIZ_STATIC_DATA';
export const START_THE_QUIZ = 'START_THE_QUIZ';